### ISSUE TITLE
Método isPair

### ISSUE THREAD

**Issue by FvFurquim** [COO-EACH-USP-2021/Poker-ACH2003-04#7]
Método que irá verificar se é pair

Assinatura:
`private boolean isPair(Card[] cards)`

**Comment by SilasReisUSP** [comment]
private boolean isPair(Card[] cards){

		for(int i = 1; i < cards.length; i++){
			if((cards[i-1].getRank() + 1) == cards[i].getRank())
				return true;
		}

		return false;
	}
